### ISSUE TITLE
Reduce Codacy issues

### ISSUE THREAD

**Issue by anuraagbaishya** [WeAreMIST/WeAreMIST.github.io#1]
Reduce the issues at https://www.codacy.com/app/baishya-anuraag1920/WeAreMIST-github-io/dashboard

**Comment by azwreith** [comment]
Issues are mostly caused by node modules, I can't remove them for the repo it's being used in the live website. I'll push a few changes to reduce issues from my code.

**Comment by azwreith** [comment]
In settings, remove node_modules, js/skel, js/jquery (3 of them), terminal.js, util.js  from the analysis.
